/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package text_adventure_remastered;

import java.awt.Dimension;
import java.awt.Toolkit;
import static text_adventure_remastered.Main.pack;

/**
 *
 * @author Isaac
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        embark = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Materials = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        restock = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextBox = new javax.swing.JTextArea();
        Save = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/house.jpg"))); // NOI18N

        embark.setText("Embark");
        embark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                embarkActionPerformed(evt);
            }
        });

        Materials.setEditable(false);
        Materials.setColumns(20);
        Materials.setRows(5);
        jScrollPane1.setViewportView(Materials);

        jLabel2.setText("Materials");

        restock.setText("Rstock");
        restock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restockActionPerformed(evt);
            }
        });

        TextBox.setColumns(20);
        TextBox.setRows(5);
        jScrollPane2.setViewportView(TextBox);

        Save.setText("Save game");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Crafting");

        jLabel3.setText("(not finished)");

        jLabel4.setText("(not finished)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(embark)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane1)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(restock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(embark)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2)
                    .addComponent(restock)
                    .addComponent(jLabel3))
                .addGap(0, 100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void embarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_embarkActionPerformed
        this.dispose();
        
        
    }//GEN-LAST:event_embarkActionPerformed
    public String newline = "\n";
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        
      PrintMaterials();
      
        
    }//GEN-LAST:event_formWindowActivated

    public void PrintMaterials(){
        
        String Food = Integer.toString(Main.pack.getFood());
        String Water = Integer.toString(Main.pack.getWater());
        String Iron = Integer.toString(Main.pack.getIron());
        String Steel = Integer.toString(Main.pack.getSteel());
        String woodenClub = Integer.toString(Main.pack.getWoodenClub());
        String Sword = Integer.toString(Main.pack.getSword());
        String Knife = Integer.toString(Main.pack.getKnife());
        String Leather = Integer.toString(Main.pack.getLeather());
        String Wood = Integer.toString(Main.pack.getWood());
        String Medicine = Integer.toString(Main.pack.medicine);
        
        Materials.setText(null);
        Materials.append("Food: " + Food + newline);
        Materials.append("Water: " + Water + newline);
        
        if(pack.leather > 0){
            Materials.append("Leather: " + Leather + newline);
        }
        if(pack.wood > 0){
            Materials.append("Wood: " + Wood + newline);
        }
        if(pack.iron > 0){
            Materials.append("Iron: " + Iron + newline);
        }
        if(pack.steel > 0){
            Materials.append("Steel: " + Steel + newline);
        }
        if(pack.medicine > 0){
            Materials.append("Medicine: " + Medicine + newline);
        }
        if("1".equals(Sword)){
            Materials.append("Weapon: Sword" + newline);
        }else if ("1".equals(Knife)){
            Materials.append("Weapon: Knife" + newline);
        }else if ("1".equals(woodenClub)){
            Materials.append("Weapon: WoodenClub" + newline);
        }
        
        
    }
    private void restockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restockActionPerformed
        
        
        
        TextBox.setText(null);
        int checkw = 0;
        int checkf = 0;
        int f = pack.food;
        int w = pack.water;
        if(pack.food < Main.MaxFood ){   
            Main.pack.setFood(Main.MaxFood);
            checkf++;
        }
        if (pack.water < Main.MaxWater){   
            Main.pack.setWater(Main.MaxWater);
            checkw++;
        }

        

        if(checkf>0){
          TextBox.append("+" + (Main.MaxFood-f) + " food" + newline);  
        }else{
          TextBox.append("+0 food" + newline);  
        }

        if(checkw>0){
            TextBox.append("+" + (Main.MaxWater-w) + " water" + newline);
        }else{
           TextBox.append("+0 water" + newline); 
        }

        PrintMaterials();
        
    }//GEN-LAST:event_restockActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Materials;
    private javax.swing.JToggleButton Save;
    private javax.swing.JTextArea TextBox;
    private javax.swing.JToggleButton embark;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton restock;
    // End of variables declaration//GEN-END:variables
}
